name: Pull Request Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Maven and Java
      - name: Set Up Maven and Java
        uses: s4u/setup-maven-action@v1.12.0
        with:
          maven-version: '3.8.4'
          java-version: '17'

      # Set up Maven settings for authentication (if necessary)
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<servers><server><id>github</id><username>${{ secrets.MAVEN_USERNAME }}</username><password>${{ secrets.MAVEN_PAT }}</password></server></servers>" > ~/.m2/settings.xml

      # Run tests and generate JaCoCo report
      - name: Run tests with JaCoCo
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PAT: ${{ secrets.MAVEN_PAT }}
        run: mvn clean verify

      # Upload JaCoCo Report as an artifact
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: auth-service/target/site/jacoco/index.html

      # JaCoCo Code Coverage Report
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: auth-service/target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      # Add JaCoCo report to workflow run summary
      - name: Add JaCoCo report to workflow run summary
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      # Post Code Coverage Results to PR
      - name: Post Code Coverage Results to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Code Coverage Report
            **Code Coverage Percentage**: ${{ steps.jacoco_reporter.outputs.coverage_percentage }}%
            
            ### Summary:
            - :heavy_check_mark: **Lines Covered**: ${{ steps.jacoco_reporter.outputs.covered_lines }}
            - :x: **Lines Missed**: ${{ steps.jacoco_reporter.outputs.missed_lines }}
            - **Total Lines**: ${{ steps.jacoco_reporter.outputs.total_lines }}

      # Fail the build if code coverage is below threshold
      - name: Check Coverage and Fail If Below Threshold
        if: steps.jacoco_reporter.outputs.coverage_percentage < 80
        run: |
          echo "Code coverage is below the threshold (80%)! Coverage: ${{ steps.jacoco_reporter.outputs.coverage_percentage }}%"
          exit 1
